site_name: Pvi.py Docs

theme: 
  name : "material"
  palette:
    primary: orange

plugins:
  - mkdocstrings
      
markdown_extensions:
  - footnotes

nav:
  - Home: "index.md"
  - Tutorials : 
      - General: tutorial/general.md
      - First Steps With ANSL: tutorial/simple1.md
      - Some More Functionality: tutorial/simple2.md
      - In Python's World: tutorial/simple4.md
      - Using INA2000.py: tutorial/simple3.md
  - PVI Objects: 
      - General: objects/general.md
      - Connection: objects/connection.md
      - Line: objects/line.md
      - Device: objects/device.md
      - Station: objects/station.md
      - Cpu: objects/cpu.md
      - Task: objects/task.md
      - Variable: objects/variable.md
      - Module: objects/module.md
      - Errors: objects/errors.md
  - How-To : 
      - Basics: howtos/basics.md
      - Multiple Connections: howtos/multiple_connections.md
      - What to do with CPUs: howtos/cpus.md
      - What to do with Tasks: howtos/tasks.md
      - Create List of Sotware Objects: howtos/object_lists.md
      - Handling Modules: howtos/modules.md
      - Linknodes (IO): howtos/linknodes.md
      - Using a GUI: howtos/gui.md
      - SNMP: howtos/snmp.md
      - Runtime Logger: howtos/logger.md
      - Profiler: howtos/profiler.md
  - Diagnosis :
      - PVI Snapshots: diagnosis/snapshot/snapshot.md
  - Reference:
      - Connection : reference/connection.md
      - PviObject : reference/object.md
      - Line: reference/line.md
      - Device : reference/device.md
      - Station : reference/station.md
      - Cpu : reference/cpu.md
      - Task : reference/task.md
      - Variable : reference/variable.md
      - Module : reference/module.md
      - PVI Errors : reference/error.md
      - Tools : reference/tools.md
  - Version history: whatsnew.md
  

  